# Generated by Django 4.0.4 on 2022-06-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApps', '0002_alter_numberphone_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberphone',
            name='discount',
        ),
    ]
