# Generated by Django 4.0.5 on 2022-07-05 05:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApps', '0004_remove_numberphone_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['create']},
        ),
        migrations.AlterField(
            model_name='filter',
            name='sub_cate',
            field=models.ManyToManyField(blank=True, default='', related_name='list_filter', to='webApps.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
