# Generated by Django 4.0.5 on 2022-07-05 06:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApps', '0005_alter_subcategory_options_alter_filter_sub_cate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_hide',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
