# Generated by Django 4.0.5 on 2022-07-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApps', '0006_subcategory_is_hide_alter_subcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberphone',
            name='is_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
