# Generated by Django 4.0.5 on 2022-07-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApps', '0007_numberphone_is_stock_order_is_finish_posts_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberphone',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberphone',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
