# Generated by Django 4.0.5 on 2022-08-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApps', '0009_alter_order_options_agentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprice',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
